<?php

namespace ENT\SiteBundle\Repository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminpageRepository extends \Doctrine\ORM\EntityRepository
{
}
