<?php

namespace ENT\SiteBundle\Repository;

/**
 * DocumentationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends \Doctrine\ORM\EntityRepository
{
}
