<?php

namespace ENT\SiteBundle\Repository;

/**
 * LogicielsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogicielsRepository extends \Doctrine\ORM\EntityRepository
{
}
