<?php

namespace ENT\SiteBundle\Repository\Security\User;

/**
 * WebServiceUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebServiceUserRepository extends \Doctrine\ORM\EntityRepository
{
}
