panel_admin:
    path:     /panel/admin
    defaults: { _controller: ENTSiteBundle:Admin:GestionAlert:index }

gestion_compte:
    path:     /panel/gcompte
    defaults: { _controller: ENTSiteBundle:Admin:GestionCompte:index }

gestion_alert:
    path:     /panel/galert
    defaults: { _controller: ENTSiteBundle:Admin:PanelAdmin:index }
