panel_admin:
    path:     /admin
    defaults: { _controller: ENTSiteBundle:Admin:GestionAlert:index }

gestion_compte:
    path:     /gcompte
    defaults: { _controller: ENTSiteBundle:Admin:GestionCompte:index }

gestion_alert:
    path:     /galert
    defaults: { _controller: ENTSiteBundle:Admin:PanelAdmin:index }
