ent_site:
    resource: "@ENTSiteBundle/Resources/config/routing.yml"
    prefix:   /

ent_site_admin:
    resource: "@ENTSiteBundle/Resources/config/admin/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
