# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
services:
    app.webservice_user_provider:
        class: ENT\SiteBundle\Security\User\WebserviceUserProvider
  #  security_context#:
  #      class:     Symfony\Component\Security\Core\SecurityContext
  #      arguments: ['@security.context']
