hello_the_world:
    path:     /
    defaults: { _controller: ENTSiteBundle:Login:connexion }
    requirements:
        _method: GET | POST
        
f_aq:
    path:     /faq
    defaults: { _controller: ENTSiteBundle:Faq:index }

lo_gin:
    path:     /login
    defaults: { _controller: ENTSiteBundle:Login:connexion }
    requirements:
        _method: GET | POST

panel_membre:
    path:     /membre
    defaults: { _controller: ENTSiteBundle:PanelClient:index }

re_ssources:
    path:     /res
    defaults: { _controller: ENTSiteBundle:Ressources:index2 }

re_sssources:
    path:     /res/{idCat}
    defaults: { _controller: ENTSiteBundle:Documentation:view }

re_ssources_id_1:
    path:     /res/1
    defaults: { _controller: ENTSiteBundle:Documentation:view }

su_pport:
    path:     /support
    defaults: { _controller: ENTSiteBundle:Support:index }

lo_out:
    path:     /logout
    defaults: { _controller: ENTSiteBundle:Security:logout }
