hello_the_world:
    path:     /world/hello
    defaults: { _controller: ENTSiteBundle:Advert:index }

f_aq:
    path:     /faq
    defaults: { _controller: ENTSiteBundle:Faq:index }

lo_gin:
    path:     /login
    defaults: { _controller: ENTSiteBundle:Security:login }

panel_membre:
    path:     /membre
    defaults: { _controller: ENTSiteBundle:PanelClient:index }

re_ssources:
    path:     /res
    defaults: { _controller: ENTSiteBundle:Ressources:index }

re_sssources:
    path:     /res/{idDocumentation}
    defaults: { _controller: ENTSiteBundle:Documentation:view }

su_pport:
    path:     /support
    defaults: { _controller: ENTSiteBundle:Support:index }

lo_out:
    path:     /logout
    defaults: { _controller: ENTSiteBundle:Security:logout }
